### ISSUE TITLE
can you explain currentPopularPersonProvider

### ISSUE THREAD

**Issue by dyardy** [Roaa94/movies_app#2]
what is the purpose of this one?

```
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:movies_app/features/people/models/person.dart';

final currentPopularPersonProvider = Provider<AsyncValue<Person>>((ref) {
  throw UnimplementedError();
});
```

**Comment by selankon** [comment]
I guess the repository is not complete. Is just a POC, because some features have missing folders

**Comment by Roaa94** [comment]
> what is the purpose of this one?
> 
> ```
> import 'package:flutter_riverpod/flutter_riverpod.dart';
> import 'package:movies_app/features/people/models/person.dart';
> 
> final currentPopularPersonProvider = Provider<AsyncValue<Person>>((ref) {
>   throw UnimplementedError();
> });
> ```

The `currentPopularPersonProvider` is the provider used inside the [`PopularPersonListItem` widget](https://github.com/Roaa94/movies_app/blob/main/lib/features/people/views/widgets/popular_person_list_item.dart#L18) and is the provider that gets populated with every list item data.

It is initialized as `UnimplementedError` at first so that its value stays non-nullable and because we are sure that we will not access this provider before we override it in the parent [`PopularPeopleList` widget](https://github.com/Roaa94/movies_app/blob/main/lib/features/people/views/widgets/popular_people_list.dart#L39)

```dart
return ProviderScope(
    overrides: [
        currentPopularPersonProvider
            .overrideWithValue(currentPopularPersonFromIndex)
    ],
    child: const PopularPersonListItem(),
);
```

And this way it's protected from being accessed without it being assigned a value (overridden) because it will throw an error.

Feel free to read about the implementation of infinite scroll in detail in the [README](https://github.com/Roaa94/movies_app#infinite-scroll-functionality)

**Comment by Roaa94** [comment]
> I guess the repository is not complete. Is just a POC, because some features have missing folders

All the features that exist in the repo are complete but there is space for extra features to be added by me or contributors.
Please let me know if there is anything missing from an existing feature.

**Comment by selankon** [comment]
> I guess the repository is not complete

I just guess it because I didn't found all the folders you describe on the `README.md` for media feature. 

Thanks for explain it (and for the repository, it was really useful)

:100:
